# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Seene' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Seene
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  target 'SeeneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SeeneUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
